### ISSUE TITLE
Check out draft version of (4 by 4) matrix multiplication template specialization

### ISSUE THREAD

**Issue by JeanYvesR** [powertechpreview/libfsmc#10]
Files are on branch 'testJean': SMatrixWithMul4x4.h and testsTemplate4x4.cpp

**Comment by pdrocaldeira** [comment]
Would you please create a pull request?
I will review it tomorrow.

Don't forget to tag this issue and the other #9 

In other words, you should add to your Pull Request the following sentence (any place):
```
This closes #9 and #10
```
